name: Check nix packages
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [master]
jobs:
  check:
    name: Check Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          send-statistics: false
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Check repository
        run: nix flake check
      - name: Build packages
        run: nix build .#${{ matrix.theme }}-grub-theme
  build:
    strategy:
      matrix:
        theme: [ acheron argenti blackswan dr.ratio hanya huohuo luocha ruanmei sparkle acheron_cn argenti_cn blackswan_cn dr.ratio_cn hanya_cn huohuo_cn luocha_cn ruanmei_cn sparkle_cn ]
    name: Build Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Build packages
        run: nix build .#${{ matrix.theme }}-grub-theme