name: Check nix packages
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [master]
jobs:
  check:
    name: Check Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          send-statistics: false
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Check repository
        run: nix flake check
  generate-matrix:
    name: Generate matrix data for build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate matrix
        run: |
          THEMES=$(ls assets/themes | tr '[:upper:]' '[:lower:]' | sed 's/\./_/g' | jq --raw-input | jq --slurp -c)

          echo "themes=$THEMES" >> $GITHUB_OUTPUT
  build:
    needs:
      - generate-matrix
    strategy:
      matrix:
        theme: ${{ fromJSON(needs.generate-matrix.outputs.themes) }}
    name: Build Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Build packages
        run: nix build .#${{ matrix.theme }}-grub-theme
